console.log("Primeira linha \n Segunda linha")
console.log("O meu nome é 'Douglas'")
console.log('O meu nome é "Roberto"')
console.log(`A multiplicação de 5 por 3 é ${5*3}`)
console.log("o " + "meu " + "é " + "'Douglas'")